spring.application.name=petvida

# Banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:petvida
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Forca o schema.sql a rodar sempre
spring.sql.init.mode=always

# Linhas obrigatorias da prova (A.2)
logging.level.web=trace
spring.thymeleaf.cache=false